### ISSUE TITLE
실행은되지만 다운이 안되요

### ISSUE THREAD

**Issue by hands8142** [J-hoplin1/Youtube-Extractor#3]
오류로그같은건 안나오는데 Wrong types of Youtube Link. Please check again. 이것만나오고 안되요 다시처음으로 돌아가요 다른걸로 해봐도 똑같아요

**Comment by J-hoplin1** [comment]
안녕하세요 Hoplin이라고합니다. 혹시 다운로드 받으시려는 유튜브 링크가 어떤건지 알려주실수 있으신가요? 우선 이 프로그램에서 지원하는 유튜브 링크 패턴은 https://www.youtube.com/watch(~~) 형태의 패턴만 지원합니다.

**Comment by hands8142** [comment]
https://youtu.be/oWiR9Ojn7JY 이거입니다

**Comment by J-hoplin1** [comment]
죄송하지만 해당 패턴 유형의 유튜브 링크는 이 프로그램에서 지원하지 않습니다. 제가 패턴을 https://www.youtube.com/watch?() 이러한 형식으로만 되게끔 설정해 놓았기에 https://www.youtube.com/watch?v=oWiR9Ojn7JY 이 URL로 다운로드 받으시면 다운로드가 되실겁니다.

**Comment by hands8142** [comment]
오 잘작동합니다 감사합니다

**Comment by J-hoplin1** [comment]
좋은하루되세요 :)

**Comment by hands8142** [comment]
넵 감사합니다
