### ISSUE TITLE
디스코드 뮤직봇도 만들어주세여

### ISSUE THREAD

**Issue by hands8142** [J-hoplin1/Youtube-Extractor#4]
디스코드 뮤직봇도 만들어주세여 해왜 영상보고 만들었는데 재생이 안되요 client.commend로 만들어주세요

**Comment by J-hoplin1** [comment]
음....지금은 딱히 디스코드 봇을 더 제작해볼 마음은 없습니다. 나중에 만들 마음이 생기면 만들어보고 알려드리죠

**Comment by J-hoplin1** [comment]
그리고 이거는 저만 불편한걸수도 있고 시비를 거는건 아니지만. 뭔가 부탁을 하시고 싶으시다면, ~만들어 보실 의향 있으신가요? 등 의문형으로 질문해주시면 감사하겠습니다. 약간 명령조로 들립니다.

**Comment by J-hoplin1** [comment]
hands8142님이 말씀하신것처럼 해외 영상을 시청해보니 디스코드 봇이 대부분 0.16.12버전의 API를 쓰는거 같더군요 현재 지원되는 API가 1.x 버전인데 제가 알기로는 Re-write버전이라 많이 달라진 부분이 있는것 같습니다. 한번 documentation읽어보면서 연구해보겠습니다 :)

**Comment by hands8142** [comment]
넵

**Comment by J-hoplin1** [comment]
hands8142님의 제안을 보고 나서 갑자기 관심이 생겼네요 ㅋㅋㅋㅋ 😄 아마 빠르면 내일 늦어도 토요일 부터 시작해볼것 같습니다 :)

**Comment by hands8142** [comment]
감사합니다
